Presentacion/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Presentacion/Controllers/PersonalTvAztecaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entidades;
using Negocio;
using System.Data;
using System.Data.Entity;
using System.Net;


namespace Presentacion.Controllers
{
    public class PersonalTvAztecaController : Controller
    {
        NegocioPersonal NP = new NegocioPersonal();
        // GET: PersonalTvAzteca
        public ActionResult Index()
        {
            List<PersonalTvAzteca> ListPersonal = NP.ConsulPersonal();

            return View(ListPersonal);

        }
        public ActionResult Create()
        {
            PersonalTvAzteca personal = new PersonalTvAzteca();
            return View(personal);
        }

        // POST: Personal/Crear
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPersonal,Nombre,PApellido,SApellido")] PersonalTvAzteca personal)
        {
            if (ModelState.IsValid)
            {
                NP.AgregarPersonal(personal);
            }
            return View(personal);


        }

        public ActionResult Consultar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PersonalTvAzteca personal = NP.ConslPersonalId(id);
            if (personal == null)
            {
                return HttpNotFound();
            }

            return View(personal);
        }
        
        public ActionResult Actualizar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PersonalTvAzteca personal = NP.ConslPersonalId(id);
            if (personal == null)
            {
                return HttpNotFound();
            }
            return View(personal);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Actualizar([Bind(Include = "IdPersonal,Nombre,PApellido,SApellido")] PersonalTvAzteca personal)
        {

            if (ModelState.IsValid)
            {
                NP.EditarPersonal(personal);
                return RedirectToAction("Index");
            }
            return View(personal);

        }
        public ActionResult Eliminar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PersonalTvAzteca personal = NP.ConslPersonalId(id);
            if (personal == null)
            {
                return HttpNotFound();
            }
            return View(personal);

        }
        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public ActionResult EliminarConfirmar(int id)
        {
            PersonalTvAzteca personal = NP.ConslPersonalId(id);
            NP.EliminarPersonal(personal);
            return RedirectToAction("Index");
        }

    }
}

Presentacion/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Presentacion/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Presentacion/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Presentacion/Views/PersonalTvAzteca/Actualizar.cshtml
@model Entidades.PersonalTvAzteca

@{
    ViewBag.Title = "Actualizar";
}

<h2>Actualizar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PersonalTvAzteca</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdPersonal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdPersonal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdPersonal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PApellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PApellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PApellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SApellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SApellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SApellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Presentacion/Views/PersonalTvAzteca/Consultar.cshtml
@model Entidades.PersonalTvAzteca

@{
    ViewBag.Title = "Consultar";
}

<h2>_Consultar</h2>

<div>
    <h4>PersonalTvAzteca</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdPersonal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdPersonal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PApellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PApellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SApellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SApellido)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink(" ", "Actualizar", new { id = Model.IdPersonal }, htmlAttributes: new { @class = "btn btn-warning glyphicon glyphicon-pencil", @title = "Actualizar" }) |
    @Html.ActionLink("Regresar", "Index")
</p>

Presentacion/Views/PersonalTvAzteca/Create.cshtml
@model Entidades.PersonalTvAzteca


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PersonalTvAzteca</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
 
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PApellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PApellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PApellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SApellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SApellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SApellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Presentacion/Views/PersonalTvAzteca/Eliminar.cshtml
@model Entidades.PersonalTvAzteca

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PersonalTvAzteca</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdPersonal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdPersonal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PApellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PApellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SApellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SApellido)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Regresar", "Index")
        </div>
    }
</div>

Presentacion/Views/PersonalTvAzteca/Index.cshtml
@model IEnumerable<Entidades.PersonalTvAzteca>

<p>
    @Html.ActionLink(" ", "Create",null, htmlAttributes: new { @class = "btn btn-info glyphicon glyphicon-user", @title = "Agregar" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdPersonal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PApellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SApellido)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdPersonal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PApellido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SApellido)
        </td>
        <td>
            @Html.ActionLink("  ", "Actualizar", new { id=item.IdPersonal }, htmlAttributes: new {@class ="btn btn-warning glyphicon glyphicon-pencil", @title = "Actualizar" }) |
            @Html.ActionLink(" ", "Consultar", new { id = item.IdPersonal }, htmlAttributes: new { @class = "btn btn-info glyphicon glyphicon-search", @title = "Consultar" }) |
            @Html.ActionLink(" ", "Eliminar", new { id = item.IdPersonal }, htmlAttributes: new { @class = "btn btn-danger glyphicon glyphicon-trash", @title = "Eliminar" })
        </td>
    </tr>
}

</table>

Presentacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand"})
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Personal", "Index", "PersonalTvAzteca")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>